### ISSUE TITLE
.SRT subtitles not picked up by local scanner

### ISSUE THREAD

**Issue by Orca2** [plexinc-agents/LocalMedia.bundle#26]
When a movie is in a folder and the folder has a different name as the actual movie, a manually added external subtitle file does not get picked up by the local media agent. example:
Folder name : Upside Down 2012
Movie name  : Upside.Down.2012.720p.BluRay.x264.YIFY.mp4
Subtitle name  : Upside.Down.2012.720p.BluRay.x264.YIFY.srt

Renaming the folder to Upside.Down.2012.720p.BluRay.x264.YIFY will fix the issue.

**Comment by sandman4sure** [comment]
@Orca2  I don't believe this is an issue anymore?

**Comment by maxGreenblatt** [comment]
Closing - cause, old. :smile:
