### ISSUE TITLE
Request to change regex to support new Frodo Season artwork namings

### ISSUE THREAD

**Issue by dettwild** [plexinc-agents/LocalMedia.bundle#28]
I would propose to changing the localmedia.py file as follows:

from:
search_tuples += [['season-?%s[-a-z]?' % metadata.index, metadata.posters, config.IMAGE_EXTS, False]]
    search_tuples += [['season-?%s-banner[-a-z]?' % metadata.index, metadata.banners, config.IMAGE_EXTS, False]]

to:
search_tuples += [['season(-|0|\s)?%s[-a-z]?(-poster)?' % metadata.index, metadata.posters, config.IMAGE_EXTS, False]]
    search_tuples += [['season(-|0|\s)?%s-banner[-a-z]?' % metadata.index, metadata.banners, config.IMAGE_EXTS, False]]

This would not only handle artwork that is named Frodo compliant, but also adds a bit of flexibility for people that use slightly different naming, e.g. Season 01.

I hope that this simple change can be included in a future release soon as I keep getting many more updates lately that overwrite my temp changes locally.

Thanks in advance for your consideration

Daniel

**Comment by mmccurdy07** [comment]
Closing, following https://github.com/plexinc/plex-media-server/issues/2057 into obscurity (apparently).
