### ISSUE TITLE
Special chars in folder names in a path causes LMA crash

### ISSUE THREAD

**Issue by atrus05** [plexinc-agents/LocalMedia.bundle#41]
A user on a QNAP has special chars in the path, and that causes the Local Media Agent to throw a critical and crash. See forum thread here: https://forums.plex.tv/topic/85424-srt-subtitles-not-recognised-in-tv-shows-section/

**Comment by sandman4sure** [comment]
see `https://github.com/plexinc/plex-media-server/issues/2817`

**Comment by OttoKerner** [comment]
I don't pretend to understand the underlying intricacies, but a user has found a one-line-fix for the QNAP platform:
https://forums.plex.tv/discussion/206148/unicode-error-with-filename-containing-german-umlauts

**Comment by ukdtom** [comment]
Heh....Found the LMA one ;-)

And: https://github.com/plexinc/plex-media-server-issues/issues/645#issuecomment-239588173
