### ISSUE TITLE
Add an "Other" category for local extras

### ISSUE THREAD

**Issue by chriscurtis** [plexinc-agents/LocalMedia.bundle#42]
Lots of users asking for additional categories for featurettes, gagreels, documentaries, and even motion comics. I don't think we either need or want a bunch more categories, but I _do_ think we could support sort of an 'everything else' `Other` (or perhaps `Miscellaneous`, though I don't think that would be quite as good as a label) category.
```
/Avatar (2009)
   Avatar (2009).mkv
   Comedy Outtakes-other.mp4
```
```
/Avatar (2009)
   Avatar (2009).mkv
   /Other
      Comedy Outtakes.mp4
```
Not sure whether the PMS side needs to be updated to add an actual category or not, too.

**Comment by maxGreenblatt** [comment]
We have scene and featurette either in the pipeline or released - not sure which?

Thought I agree an `-other` or `-misc` would be nice.

I think @sandman4sure is the right person for this one as he just added the two mentioned above.

**Comment by chriscurtis** [comment]
"Short" and "Featurette" support have both been added (at least in the 0.9.14.something versions). Were we to add an "everything else" type category, I'd still vote for `Other`, I think.

**Comment by sandman4sure** [comment]
Closed, see https://github.com/plexinc/pms-bundle-issues/issues/3
