### ISSUE TITLE
Map track genres into album/artist genres for music

### ISSUE THREAD

**Issue by chriscurtis** [plexinc-agents/LocalMedia.bundle#45]
ID3 tags are associated with tracks, so it's not possible to specify the genre for an _album_ via embedded metadata. It would be good to somehow map the most common (or multiple) genre for tracks within an album to the album itself.

(As it stands, if a user doesn't pull genre data from Last.fm then they won't have any genre information for albums, only individual tracks.)

**Comment by sandman4sure** [comment]
As of now, Album will get the genre of one of the songs from that album.
In commit `https://github.com/plexinc-agents/LocalMedia.bundle/commit/c728e242c5c5f3334dafead55fdbb0015650539f` I added genre for artist: it will get the genre from a track from every album it contains.

**Comment by sandman4sure** [comment]
all genres from the tracks are used for album and artist. 
https://github.com/plexinc-agents/LocalMedia.bundle/commit/375b8cef62a3c010b87a90d0a4d46bb2a7bf86e7
(this fix is not live yet)
An artist can have multiple genres and those all will be used by the filters, but only two are shown in f.i. Plex/Web

I think this solves this issue, right? Please reopen if I missed anything.
