### ISSUE TITLE
Invalidly-named inline extras cause all local media assets to be ignored

### ISSUE THREAD

**Issue by chriscurtis** [plexinc-agents/LocalMedia.bundle#47]
@BigWheel88's #46 is sort of similar to and reminded me of something I saw recently when I was trying to test having multiple sidecar subtitles of the same language for a user.

Failed (no subtitles found):
```
/Alien (1979)
   Alien (1979).mkv
   Alien (1979) 1.eng.srt
   Alien (1979) 2.eng.srt
   Inline BtS-behindthescenes.mkv
```
Worked (subtitles found):
```
/Alien (1979)
   Alien (1979).mkv
   Alien (1979) 1.eng.srt
   Alien (1979) 2.eng.srt
   /Behind the Scenes
      Performance Capture.mkv
```
It was an issue having multiple sidecar subs together with inline extras. With an inline extra, the subs are not found, but if the extra is put in a subdirectory then things work.

Now, to be fair, we don't claim to support multiple sidecar subs of the same language, so the naming I used for them is "wrong". So we could probably say `won't fix` because "you're doing it wrong" if we wanted. (Things work fine with a single sidecar sub correctly named "Alien (1979).eng.srt")

**Comment by sandman4sure** [comment]
It looks like this is done intentionally:

`If we have more than one media file within the folder and located filename (of the subtitle) doesn't match exactly then we should simply ignore it.`

If there is more than one media file there is no way to know to which file the subtitles belong to, so we ignore them. If there is only one media file, every name for the subtitle is good.

I don't know if we should change this behavior.

**Comment by atrus05** [comment]
It is easy to support up to 3 different subs for one language. Lets use Alien as example again:
Alien (1979).mkv
Alien (1979).en.srt
Alien (1979).eng.srt
Alien (1979).english.srt

**Comment by sandman4sure** [comment]
It's possible to add as many as you like afaik:
```Alien (1979).mkv```
```Alien (1979) 1.en.srt```
```Alien (1979) 2.en.srt```
```Alien (1979) 3.en.srt```
```subtitle.en.srt```

This will work if you have only one media file in the folder

**Comment by atrus05** [comment]
Yeah, sorry, what I meant was that if you have more than one media file you can still use 3 files for one language with my technique.

**Comment by maxGreenblatt** [comment]
Closing as WF - reopen if this isn't correct.
