### ISSUE TITLE
Single-word home videos getting wrong titles?

### ISSUE THREAD

**Issue by mmccurdy** [plexinc-agents/LocalMedia.bundle#54]
investigate, per https://github.com/plexinc/plex-media-server-issues/issues/211

**Comment by mmccurdy07** [comment]
I can't repro this...  it seems like the scanner may initially return names with extensions, but the LocalMedia agent cleans them up.  Is something about your setup preventing the LocalMedia agent from running?  /cc @diamondsw

If not, can you give me a specific set of files that reproduces it?

**Comment by diamondsw** [comment]
Not that I'm aware of, although I did notice some other agent oddities lately (namely, new TV shows come up with raw data from disk on the first scan, and only pull in data from TheTVDB on subsequent scans). Let me reset things on my PMS and see if that helps.

**Comment by diamondsw** [comment]
It's not any specific file, but the latest one that caused it was called "Prismatic.mp4", which ended up in Plex as "Prismatic Mp4". I don't see anything awry in how the section was created - the scanner is "Plex Video Files Scanner" and agent is "Personal Media". The "Personal Media Shows" agent has "Local Media Assets (TV)" and "Personal Media Shows" in that order. Should be as straightforward as it gets.

**Comment by sandman4sure** [comment]
I notice the same as Mike above. You see for a brief second the Mp4 after the name (in Plex Web) and after that it renames to Prismatic.
Maybe you have an error which prevents getting to the renaming part. Can you please upload your logs after you have added this video?

**Comment by sandman4sure** [comment]
@diamondsw can you please upload all logs after adding this video?
As stated above I see the wrong title for a brief second, but after that it fixes itself.

**Comment by maxGreenblatt** [comment]
No update in 2.5 months. Closing. Please re-open if this is still an issue.
