### ISSUE TITLE
Add support for flagging sidecar subs as "forced"

### ISSUE THREAD

**Issue by chriscurtis** [plexinc-agents/LocalMedia.bundle#55]
We support reading in the "forced" flag for embedded subtitles in an MKV container. It would be nice to be able to specify that a sidecar subtitle file is "forced". Perhaps key off the filename scheme `[media filename].[eng]-forced.srt`

**Comment by sandman4sure** [comment]
with this fix you can flag the subtitle as follows:

`[moviename name].[language code].[forced,default,normal].srt`
`forced` and `default` are recognized by PMS, normal is just ignored for now (I have added it because people coming from kodi can have this in the subtitle name)

**Comment by sandman4sure** [comment]
Oke, all committed to master. If this goes live for everyone, we probably need to update the support docs.
