### ISSUE TITLE
Is it possible to specify the priorities in selecting the default poster?

### ISSUE THREAD

**Issue by xct24** [plexinc-agents/LocalMedia.bundle#68]
Hi there, Thank you for your wonderful work!

I'm using another software for importing video files into the server which also includes two different image files with the same name but different extension (.jpg vs. .png), and the server automatically choose the .jpg file as the default poster. I wonder if I can manipulate this or I have to change each of them manually.

Thanks again!

**Comment by maxGreenblatt** [comment]
There isn't a use friendly setting to change this. It would require a code change in the agent (and maybe the scanner).

Unfortunately, I don't think we could change the current behavior as it is expected, but if you want to make the changes for your personal server you would be welcome to do so.

**Comment by xct24** [comment]
Thanks for your quick response! I totally understand it. I wonder if it's possible to find out the exact rules of priorities for default poster so I can change the name of the images instead?

Thank you again!

**Comment by maxGreenblatt** [comment]
```Multiple Poster Images

More than one poster image can be included. The poster used can be selected in the Plex Web App. For multiple items to be scanned, they should be named as follows:
Custom_Poster_Name-X.ext
Where -X is a number```

https://support.plex.tv/hc/en-us/articles/200220677-Local-Media-Assets-Movies

**Comment by xct24** [comment]
Thank you!
